# Project: TicTacToe
# Makefile created by Dev-C++ 5.2.0.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = TicTacToe_private.res
OBJ      = ../src/main.o $(RES)
LINKOBJ  = ../src/main.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -L"../vendor/bgi/lib" -mwindows -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32  
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"  -I"../vendor/bgi/include" 
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"  -I"../vendor/bgi/include" 
BIN      = ../bin/TicTacToe.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS   = $(INCS)  
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ../bin/TicTacToe.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "..\bin\TicTacToe.exe" $(LIBS)

../src/main.o: ../src/main.cpp
	$(CPP) -c ../src/main.cpp -o ../src/main.o $(CXXFLAGS)

TicTacToe_private.res: TicTacToe_private.rc 
	$(WINDRES) -i TicTacToe_private.rc --input-format=rc -o TicTacToe_private.res -O coff 
